export const TORONTO_SCHOOLS = [
  "A.Y. Jackson Secondary School",
  "Agincourt Collegiate Institute",
  "Albert Campbell Collegiate Institute",
  "Archbishop Romero Catholic Secondary School",
  "Birchmount Park Collegiate Institute",
  "Bishop Allen Academy",
  "Bishop Marrocco/Thomas Merton Catholic Secondary School",
  "Bloor Collegiate Institute",
  "C. W. Jefferys Collegiate Institute",
  "Cardinal Carter Academy for the Arts",
  "Cardinal Newman Catholic High School",
  "Cedarbrae Collegiate Institute",
  "Central Technical School",
  "Central Toronto Academy",
  "Chaminade College School",
  "Danforth Collegiate and Technical Institute",
  "Don Mills Collegiate Institute",
  "Downsview Secondary School",
  "Dr. Norman Bethune Collegiate Institute",
  "Earl Haig Secondary School",
  "East York Collegiate Institute",
  "Emery Collegiate Institute",
  "Etobicoke Collegiate Institute",
  "Etobicoke School of the Arts",
  "Father Henry Carr Catholic Secondary School",
  "Father John Redmond Catholic Secondary School",
  "Forest Hill Collegiate Institute",
  "Francis Libermann Catholic High School",
  "Georges Vanier Secondary School",
  "Harbord Collegiate Institute",
  "Humberside Collegiate Institute",
  "Jarvis Collegiate Institute",
  "L'Amoreaux Collegiate Institute",
  "Lawrence Park Collegiate Institute",
  "Leaside High School",
  "Lester B. Pearson Collegiate Institute",
  "Loretto Abbey Catholic Secondary School",
  "Loretto College School",
  "Madonna Catholic Secondary School",
  "Malvern Collegiate Institute",
  "Marc Garneau Collegiate Institute",
  "Marshall McLuhan Catholic Secondary School",
  "Mary Ward Catholic Secondary School",
  "Michael Power/St. Joseph High School",
  "Monarch Park Collegiate Institute",
  "Neil McNeil High School",
  "Newtonbrook Secondary School",
  "North Albion Collegiate Institute",
  "North Toronto Collegiate Institute",
  "Northern Secondary School",
  "Northview Heights Secondary School",
  "Notre Dame High School",
  "Oakwood Collegiate Institute",
  "Parkdale Collegiate Institute",
  "R. H. King Academy",
  "Richview Collegiate Institute",
  "Riverdale Collegiate Institute",
  "Rosedale Heights School of the Arts",
  "Runnymede Collegiate Institute",
  "SATEC @ W.A. Porter Collegiate Institute",
  "Senator O'Connor College School",
  "Silverthorn Collegiate Institute",
  "Sir John A. Macdonald Collegiate Institute",
  "Sir Oliver Mowat Collegiate Institute",
  "Sir Wilfrid Laurier Collegiate Institute",
  "St. Basil-the-Great College School",
  "St. Brother André Catholic High School",
  "St. John Henry Newman Catholic High School",
  "St. Joseph's College School",
  "St. Mary's Catholic Academy",
  "St. Michael's Choir School",
  "St. Patrick Catholic Secondary School",
  "Stephen Leacock Collegiate Institute",
  "Thistletown Collegiate Institute",
  "Victoria Park Collegiate Institute",
  "W. L. Mackenzie Collegiate Institute",
  "West Hill Collegiate Institute",
  "West Humber Collegiate Institute",
  "Western Technical-Commercial School",
  "Westview Centennial Secondary School",
  "Wexford Collegiate School for the Arts",
  "William Lyon Mackenzie Collegiate Institute",
  "Winston Churchill Collegiate Institute",
  "York Memorial Collegiate Institute",
  "York Mills Collegiate Institute"
].sort();

export const NEIGHBORHOODS = [
  "Agincourt",
  "Bayview Village",
  "Beaches / East York",
  "Central Toronto / Midtown",
  "Don Mills",
  "Downtown Toronto",
  "Downsview",
  "Etobicoke Center",
  "Etobicoke North",
  "Etobicoke South",
  "High Park / Parkdale",
  "Leslieville / Riverdale",
  "Newtonbrook",
  "North York Center",
  "Scarborough Center",
  "Scarborough North",
  "Scarborough South",
  "Willowdale",
  "York / Weston",
  "York Mills",
  "Other"
];

export const OPPORTUNITY_CATEGORIES = [
  'Animal Welfare',
  'Arts & Culture',
  'Children & Youth',
  'Community Services',
  'Education',
  'Environment',
  'Event Planning',
  'Food Banks',
  'Health & Hospitals',
  'Seniors',
  'Sports',
  'Technology',
  'Tutoring',
  'Other'
];

export const OPPORTUNITY_EXCLUSIVES = [
  'Club Exclusive',
  'School Exclusive',
  'Local Residents',
  'Disability Accessible',
  'Grade 9 Only',
  'Grade 10 Only',
  'Grade 11 Only',
  'Grade 12 Only'
];
