import type { StudentProfile } from '../../types';

/**
 * Builds the printable Ontario community-involvement transcript.
 *
 * Extracted from StudentDashboard, where 105 lines of HTML string-building sat
 * inside the component between two state handlers. It is a pure function of the
 * profile and the hour total, so it does not belong in a React component at all
 * — and keeping it there meant every read of the dashboard had to scroll past a
 * full HTML document.
 *
 * Values are escaped on the way in. This document is opened in a new window and
 * printed, so an unescaped student name or activity description would be live
 * HTML in a page the student is about to hand to their school.
 */
export function buildCertificateHtml(
  studentProfile: Partial<StudentProfile> | null | undefined,
  totalCompletedHours: number | string,
): string {

  const escapeHTML = (str: any) => {
    if (typeof str !== 'string') return String(str || '');
    return str
      .replace(/&/g, '&amp;')
      .replace(/</g, '&lt;')
      .replace(/>/g, '&gt;')
      .replace(/"/g, '&quot;')
      .replace(/'/g, '&#39;');
  };

  // One row per activity, shaped to what an Ontario board form actually asks
  // for — see the note at the top of this file.
  //
  // `organization` is read with a fallback chain because it has only recently
  // been carried onto the logged entry; older entries baked it into the
  // activity text instead, and the column must not read blank for those.
  const tableRows =
    (studentProfile?.loggedHours || [])
      .map(
        (lh: any) => `
    <tr>
      <td>${escapeHTML(lh.date)}</td>
      <td style="text-align: center; font-weight: 700;">${escapeHTML(lh.hours)}</td>
      <td>${escapeHTML(lh.activity)}</td>
      <td>${escapeHTML(lh.organization || lh.orgName || '')}</td>
      <td>
        ${escapeHTML(lh.coordinatorName || '')}
        ${lh.coordinatorContact ? `<br><span class="muted">${escapeHTML(lh.coordinatorContact)}</span>` : ''}
      </td>
      <td class="sign">${
        lh.approvedAt
          ? `<span class="muted">Confirmed in app<br>${escapeHTML(String(lh.approvedAt).slice(0, 10))}</span>`
          : ''
      }</td>
      <td class="sign"></td>
    </tr>
  `,
      )
      .join("") ||
    `<tr><td colspan="7" style="padding: 24px; text-align: center; color: #94a3b8; font-style: italic;">No volunteer hours logged yet.</td></tr>`;

  return (`
    <html>
      <head>
        <title>Community Involvement Hours</title>
        <style>
          @page { margin: 14mm; }
          body { font-family: system-ui, -apple-system, "Segoe UI", sans-serif; color: #0f172a; font-size: 12px; line-height: 1.45; }
          h1 { font-size: 17px; margin: 0 0 2px; }
          .sub { font-size: 11px; color: #475569; margin: 0 0 14px; }
          .ident { width: 100%; border-collapse: collapse; margin-bottom: 14px; }
          .ident td { padding: 5px 8px; border: 1px solid #cbd5e1; }
          .ident .label { background: #f1f5f9; font-weight: 600; width: 130px; white-space: nowrap; }
          table.log { width: 100%; border-collapse: collapse; }
          table.log th, table.log td { border: 1px solid #cbd5e1; padding: 6px 7px; vertical-align: top; text-align: left; }
          table.log th { background: #f1f5f9; font-size: 10px; text-transform: uppercase; letter-spacing: .03em; }
          table.log tr { break-inside: avoid; }
          td.sign { min-width: 110px; height: 34px; }
          .muted { color: #64748b; font-size: 10px; }
          .total { margin-top: 10px; font-size: 13px; font-weight: 700; text-align: right; }
          .declare { margin-top: 18px; border-top: 2px solid #0f172a; padding-top: 10px; }
          .declare p { margin: 0 0 10px; font-size: 11px; }
          .sigrow { display: flex; gap: 26px; margin-top: 22px; }
          .sigrow div { flex: 1; border-top: 1px solid #0f172a; padding-top: 4px; font-size: 10px; color: #475569; }
          .note { margin-top: 14px; font-size: 10px; color: #64748b; }
        </style>
      </head>
      <body>
        <h1>Community Involvement Hours</h1>
        <p class="sub">
          Ontario Secondary School Diploma requirement &middot; 40 hours
          &middot; Record generated by Volunteer North York
        </p>

        <table class="ident">
          <tr>
            <td class="label">Student name</td><td>${escapeHTML(studentProfile?.fullName || '')}</td>
            <td class="label">Student number</td><td></td>
          </tr>
          <tr>
            <td class="label">School</td><td>${escapeHTML(studentProfile?.school || '')}</td>
            <td class="label">Grade</td><td>${escapeHTML(studentProfile?.grade || '')}</td>
          </tr>
        </table>

        <table class="log">
          <thead>
            <tr>
              <th style="width: 74px;">Date completed</th>
              <th style="width: 46px;">Hours</th>
              <th>Description of activity</th>
              <th style="width: 130px;">Organization</th>
              <th style="width: 140px;">Supervisor name &amp; contact</th>
              <th style="width: 110px;">Supervisor signature</th>
              <th style="width: 110px;">Pre-approval (initial)</th>
            </tr>
          </thead>
          <tbody>
            ${tableRows}
          </tbody>
        </table>

        <p class="total">Total hours: ${escapeHTML(totalCompletedHours)} of 40</p>

        <div class="declare">
          <p>
            I certify that the information recorded above is accurate and that these
            hours were completed as described.
          </p>
          <div class="sigrow">
            <div>Student signature &nbsp;&middot;&nbsp; Date</div>
            <div>Parent / guardian signature &nbsp;&middot;&nbsp; Date <span class="muted">(required if under 18)</span></div>
          </div>
          <div class="sigrow">
            <div>Principal / designate &nbsp;&middot;&nbsp; Date</div>
            <div>&nbsp;</div>
          </div>
        </div>

        <p class="note" style="border:2px solid #1F4C63; padding:10px 12px; font-size:12px; line-height:1.5;">
          <strong style="font-size:13px;">This is not an official school document.
          You still need your school board's own community involvement form, signed
          by your supervisor.</strong><br>
          Hours shown were confirmed in Volunteer North York by the named supervisor.
          Use this sheet to help you fill in your board's form &mdash; the signature
          and pre-approval columns above are left blank for ink.
        </p>
      </body>
    </html>
  `);
}
